### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by edg2s** [TRowbotham/PHPJS#5]
There are standard test suites for the DOM that would help catch issues like #3 & #4.

**Comment by TRowbotham** [comment]
Coincidentally, I do have quite a few unit tests written from the [web-platform-tests](https://github.com/web-platform-tests) repository, but I never committed them. Most of the ones I have cover methods for Node and Document. I'll work on cleaning up the existing tests and porting over some of the tests for ranges.

**Comment by TRowbotham** [comment]
I finally got around to unbreaking the tests I had and wrote a ton of new ones. Still along way to go, but this should be a good start.

```bash
Time: 03:24.241, Memory: 157.47 MB

There were 65 errors:

<snip>

ERRORS!
Tests: 28034, Assertions: 131548, Errors: 65, Failures: 19, Skipped: 6, Incomplete: 16.
```

The errors are all from Range::insertNode(), which needs more investigation. 

All the failures currently revolve around string casting, because casting null to a string in JavaScript produces "null", but in PHP casting null produces "". I haven't really decided what to do about this, but I'm leaning towards changing the test expectations to match PHP's string casting behavior.

The Range tests make up the majority of the test runtime, as the tests create something like 26,000+ Ranges and my attempts at trying to clean them up have failed thus far.

Code coverage is just slightly above 40%.

**Comment by TRowbotham** [comment]
I pushed out an update today with bug fixes and a lot more tests. There are roughly 11,000 new tests and 50,000 new assertions, which brings the total code coverage to over 83%.

```bash
Time: 02:21.247, Memory: 253.72 MB

There were 5 errors:

<snip>

ERRORS!
Tests: 38979, Assertions: 180609, Errors: 5, Failures: 62, Skipped: 16, Incomplete: 16.
```

The performance of the Range tests continues to be a concern as it accounts for roughly 75% of test suite's total run time.

**Comment by edg2s** [comment]
cc @MatmaRex

**Comment by MatmaRex** [comment]
Uh, yeah, I have a few other minor optimization patches for the Range code that I was hesitating to submit. No idea if they touch any of the things that are slow in your tests. https://gerrit.wikimedia.org/r/q/project:mediawiki/extensions/DiscussionTools+topic:optimize

They're on top of our "fork" of your code (since we're using it to operate on the built-in PHP DOM objects), so I'll have to rewrite some stuff when submitting here.

**Comment by MatmaRex** [comment]
I've submitted pull requests now (#8 #9 #10), but they don't seem to have any impact on the test suite run time.

**Comment by TRowbotham** [comment]
Thanks, I'll take a look at those pull requests tomorrow.

There are a number of issues with things regarding the performance of the Range tests:

The tests themselves:
1) Many of the data providers currently return `Range` objects, which means that PHPUnit is holding a reference to every range created by the tests, since it keeps data providers around in case you want to call `--repeat` or the like. The downside is this keeps many objects alive even after the test has finished running.
2) The range tests make heavy use of `eval()`, which is slow and allocates memory that cannot be released until after the script has finished running.

The code itself:
1) For each Range object created, a reference to that Range object is inserted in to a static list.
2) We must keep track of these range objects so that DOM tree mutation methods, such as `Node::appendChild()` and `Text::splitText()`, can mutate these range objects.
3) As an example, step 7 for [splitting text](https://dom.spec.whatwg.org/#concept-text-split) like in `Text::splitText()` says to loop over this static list of Range objects 4 times, looking for Range objects that meet a specific criteria.
4) In the test suite, the size of the static list grows to over 26,000 `Range` objects, which means that each call to a method that mutates the DOM tree would end up looping roughly 104,000 times.
5) We try to reduce the size of this static list when a `Document` object is destroyed, but because we hold a reference to every Range object, it never gets destroyed, and those Range objects hold references to nodes in documents, which means that the document is never destroyed and the static list of ranges continues to grow.

Ideally, we would remove Range objects from the static list when there are no more references being held for that object, but we don't have access to an object's ref count. I did a quick test, modifying the tests data providers and using the `WeakReference` class introduced in PHP 7.4 with the static list of Range objects, and this dropped the run time from about 1 minute 45 seconds to about 7 seconds. A massive difference in performance.

There are certainly many places that could be better optimized to improve performance further, but for the most part, I'm not sure there is much that can be done on PHP versions less than 7.4 when there are that many Range objects involved.

One place to try to get a big win would be to see if we can loop over the static list of ranges once in methods that modify the DOM tree, collecting all the range objects that we need to mutate, then only loop over those `Range` objects. But, I would need to check to see if mutating a range in a previous step would make it match the criteria in a subsequent step.

**Comment by TRowbotham** [comment]
I've pushed some updates on top of your pull requests that significantly improve the performance when dealing with many Ranges. On PHP 7.4, the test suite run time has dropped to 14 seconds, which is down from 2.5 minutes.

**Comment by TRowbotham** [comment]
Closing as code coverage has reached 90%.
